### ISSUE TITLE
Naming style violations

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-report_offlinequizcron#1]
Places like https://github.com/academic-moodle-cooperation/moodle-report_offlinequizcron/blob/3bd4a600dcbf02eebd7b218087e05776de22ac55/locallib.php#L39 violate guidelines as per https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

Best to refactor and move such into auto-loaded classes.

Functions like `offlinequizcron_display_job_list` should be renamed to have prefix `report_offlinequizcron_...`

**Comment by mkemmerling** [comment]
Thanks for reporting, we have included it in our backlog.

**Comment by goggo24** [comment]
It's fixed in v.3.10.1 and 3.11.0.
