### ISSUE TITLE
Write actions are not protected against CSRF - missing sesskey

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-report_offlinequizcron#2]
The script resubmit.php does not require `sesskey` to be provided as a parameter. It could be abused for CSRF attack that might cause re-processing of offline quizzes.

Ref: https://docs.moodle.org/dev/Security:Cross-site_request_forgery

**Comment by mkemmerling** [comment]
Thanks for reporting, we have included it in our backlog.

**Comment by goggo24** [comment]
It's fixed in v.3.10.1 and v3.11.0.
